<a href="https://colab.research.google.com/github/yrhutu21/Data_Science_MIniProjects/blob/main/Task6_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv('/content/Dataset .csv')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [3]:
#New feature creation
df['Name Length'] = df['Restaurant Name'].apply(len) #Count no of characters
df[['Restaurant Name', 'Name Length']].head()

          Restaurant Name  Name Length
0        Le Petit Souffle           16
1        Izakaya Kikufuji           16
2  Heat - Edsa Shangri-La           22
3                    Ooma            4
4             Sambo Kojin           11

In [4]:
#Creation of Address length
df['Address Length'] = df['Address'].apply(len)
df[['Address', 'Address Length']].head()

                                             Address  Address Length
0  Third Floor, Century City Mall, Kalayaan Avenu...              71
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...              67
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...              56
3  Third Floor, Mega Fashion Hall, SM Megamall, O...              70
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...              64

In [5]:
#Table Booking
df['Has Table Booking'] = df['Has Table booking'].map({'Yes': 1, 'No': 0})
df[['Has Table booking', 'Has Table Booking']].head()

  Has Table booking  Has Table Booking
0               Yes                  1
1               Yes                  1
2               Yes                  1
3                No                  0
4               Yes                  1

In [6]:
#Online Delivery
df['Has Online Delivery'] = df['Has Online delivery'].map({'Yes': 1, 'No': 0})
df[['Has Online delivery', 'Has Online Delivery']].head()

  Has Online delivery  Has Online Delivery
0                  No                    0
1                  No                    0
2                  No                    0
3                  No                    0
4                  No                    0

In [7]:
#Number of Cuisines
df['Number of Cuisines'] = df['Cuisines'].apply(lambda x: len(str(x).split(',')))
df[['Cuisines', 'Number of Cuisines']].head()

                           Cuisines  Number of Cuisines
0        French, Japanese, Desserts                   3
1                          Japanese                   1
2  Seafood, Asian, Filipino, Indian                   4
3                   Japanese, Sushi                   2
4                  Japanese, Korean                   2

In [8]:
#Saving of updated dataset
df.to_csv("processed_dataset.csv", index=False)